### ISSUE TITLE
Incorrect data type in unit tests

### ISSUE THREAD

**Issue by mbenson1** [nasa/CS#1]
The CS_HousekeepingCmd_Test_Nominal() function in the cs_app_test.c file sets:

CS_AppData.RecomputeInProgress  = 10;
CS_AppData.OneShotInProgress    = 11;

The associated member attributes in the HK message are uint8, but the member attribute in the CS_AppData struct is type boolean.  This still compiles and passed with older versions of the OSAL, but with OSAL 6.7.3-bv this compiles but fails unit test. I recommend changing assignments from 10 and 11 to both true, and the equality check from 10 and 11 to 1.  When this change is made, CS passes unit testing.

**Comment by ejtimmon** [comment]
I've added this to our internal issue tracker.  This will be addressed in the next release of CS.

**Comment by skliper** [comment]
The update was in 0f34b32d49eafec36f498c04cac2d2e0bac0cae6, unit test passes in 7c2d61f22314e04925194f70204a2bc9442bafb6.
