### ISSUE TITLE
CS Seg Faults when using memory definition table (CS.DefMemoryTbl)

### ISSUE THREAD

**Issue by dmknutsen** [nasa/CS#25]
**Describe the bug**
On a 64-bit system, CS will intermittently seg fault when it attempts to checksum an address defined by the memory definition table (CS.DefMemoryTbl).  Further, when you dump the results table for a given address defined  by the memory definition table - the address is byte swapped...which I do not believe to be the expected result and may help in de-bugging this issue.

**To Reproduce**
1. Start cFS
2. Load/validate/activate a memory definition table with a non-zero address
3. Observe Seg fault when CS attempts to checksum the entry with non-zero starting address.

**System observed on:**
Oracle VM VirtualBox
OS: ubuntu-20.10
Versions: cFS Versions: cfe v7.0.0-rc4+dev96, osal v6.0.0-rc4+dev66, psp v1.6.0-rc1+dev14.

**Reporter Info**
Dan Knutsen
NASA Goddard

**Comment by astrogeco** [comment]
[CCB:2022-05-04](https://github.com/nasa/cFS/wiki/CCB:-2022.05.04) Discussed
- Create table *after* you know what the valid addresses are 
- Use dynamic lookup to choose a valid symbol in testing
- @dmknutsen to test manually and show that this works before closing
- Can we protect against segfaults?
- Should we deprecate hard-coded addresses in tables? What are the use cases? Are they frequent enough?
- This functionality can be replicated using the "one shot" checksum command

**Comment by dmknutsen** [comment]
We are looking into the possibility of creating 'tables on the fly' for CTF testing.  This issue can be closed because the seg faults are the expected Linux behavior.

**Comment by skliper** [comment]
Just to clarify - the memory definition table memory addresses and sizes all need to be valid or a SEGFAULT could occur due to CS attempting to read invalid memory.  The PSP could catch a SEGFAULT and handle it if needed.
