### ISSUE TITLE
Add scrubbing support for libraries

### ISSUE THREAD

**Issue by jhnphm** [nasa/CS#27]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/CS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [README file](https://github.com/nasa/CS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
CS currently doesn't support scrubbing libraries. This could be implemented now that ticket https://github.com/nasa/cFE/issues/28 is implemented.

**Describe the solution you'd like**
Add a field in the app table to specify whether or not an entry belongs to an app or a lib and call the appropriate API functions accordingly

**Describe alternatives you've considered**
Add a separate dedicated lib table, or perhaps call CFE_ES_GetAppIDByName first and if that fails, call CFE_ES_GetLibIDByName, then call CFE_ES_GetModuleInfo() to get the addresses to scrub

**Requester Info**
John N Pham, Northrop Grumman

**Comment by skliper** [comment]
I like just trying `CFE_ES_GetAppIDByName`, then `CFE_ES_GetLibIDByName` if the former fails.
