### ISSUE TITLE
`CS_CMD_MID` and `CS_HK_TLM_MID` share duplicate CCSDS APID fields with other apps

### ISSUE THREAD

**Issue by thnkslprpt** [nasa/CS#90]
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the issue**
`CS_CMD_MID` has the same APID value as `HK_COMBINED_PKT4_MID`
`CS_HK_TLM_MID` has the same APID value as `LC_CMD_MID`

They are obviously still differentiated by the packet type field (4th bit) but this is still a bit of an unnecessary risk and potentially confusing duplication. Seems preferable for the APIDs to be unique across a cFS (+ apps) instance.

```c
// 000 1 1 00010011111 CS_CMD_MID
// 000 0 1 00010011111 HK_COMBINED_PKT4_MID

// 000 0 1 00010100100 CS_HK_TLM_MID
// 000 1 1 00010100100 LC_CMD_MID
```

On a related note, a couple of other apps/components reuse identical APIDs within their own namespace, also only differentiated by the packet type bit.

_**Is this a problem?**_

**Reporter Info**
Avi Weiss &nbsp; @thnkslprpt

**Comment by skliper** [comment]
Not typically a concern since the MID is unique.
